---
title: "R Notebook"
output: html_notebook
---


```{r}
library(readr)
library(stringr)
library(dplyr)
library(httr)
library(jsonlite)
```




```{r}
muestra <- read_csv("muestra_resumen_distrito.csv", col_types = cols(.default = "c"))
mapper <- read_csv("map_candidates_to_viz.csv")
ubigeo_mapper <- read_csv("tabla_equivalencias - Hoja 1.csv")
no_contar <- c("TOTAL DE VOTOS EMITIDOS", "VOTOS EN BLANCO", "VOTOS NULOS", "TOTAL DE VOTOS VÃLIDOS")
```



```{r}
# select(muestra, ACTAS_PROCESADAS, POR_PROCESAR, POR_POR_PROCESAR) %>% sample_n(10)
# filter(bruto, dep=="AMAZONAS") %>% filter(!AGRUPACION %in% no_contar) %>%  arrange(desc(total))
# filter(bruto, dep=="AMAZONAS") %>% filter(!AGRUPACION %in% no_contar) %>% summarise(sum(total))
# filter(bruto, dep=="AMAZONAS") %>% filter(!AGRUPACION %in% no_contar) %>% summarise(sum())
```

```{r}
avance_procesamiento_dep <- 
    distinct(muestra, dep, prov, dist, ACTAS_PROCESADAS, POR_PROCESAR) %>% 
    mutate(
        dep = if_else(dep == "LIMA" & prov != "LIMA", "LIMA-PROVINCIAS", dep)
    ) %>% 
    group_by(dep) %>% 
    summarise(
        por_procesar = sum(as.numeric(POR_PROCESAR), na.rm=T),
        procesadas = sum(as.numeric(ACTAS_PROCESADAS), na.rm=T),
        total_actas = por_procesar + procesadas, 
        porcentaje_procesada = procesadas/total_actas *100
    )
general <- avance_procesamiento_dep %>% 
    summarise(
        procesadas = sum(procesadas),
        total = sum(total_actas),
        avance = procesadas/total
    )
avance_general <- general$avance * 100
general
```

```{r}
avance_procesamiento_dep
```



```{r}
# vista_general <- content(httr::GET("https://api.resultadossep.eleccionesgenerales2021.pe/results/10/000000?name=param"), as="parsed")
vista_general <- read_json("000000.json")
avance_general <- as.numeric(vista_general$generals$generalData$POR_ACTAS_PROCESADAS)
hora_general <- paste(vista_general$generals$actData$HORA, vista_general$generals$actData$FECHA, sep=" - ")
```



```{r}
ubigeos_dep <- 
    muestra %>% 
    distinct(ubigeo, dep) %>%
    mutate(nuevo =  paste0( str_sub(ubigeo, 1, 2), "0000")  ) %>% 
    distinct(nuevo, dep) %>% arrange(desc(nuevo)) %>% filter(str_sub(nuevo,1,1) %in% c("1","2", "0")) %>% 
    bind_rows(
        tibble(dep=c("EXTRANJERO", "TOTAL"), nuevo =c("900000", "000000") )
    ) %>% 
    apply(1, function(x){
        dep <- x[1]
        
        
        # urldep <- paste0("https://api.resultadossep.eleccionesgenerales2021.pe/results/10/", x[2],"?name=param")
        # vista_url <- content(httr::GET(urldep), as="parsed")
        vista_url <- read_json(paste0(x[2], ".json"))
        
        tibble(
            "fecha"=vista_url$generals$actData$FECHA, 
            "hora"=vista_url$generals$actData$HORA,
            "por_actas_procesadas"=vista_url$generals$generalData$POR_ACTAS_PROCESADAS,
            "dep"=dep,
            "candidato" = c(vista_url$results[[1]]$NOMBREe_CANDIDATO,vista_url$results[[2]]$NOMBREe_CANDIDATO),
            "por_validos" = c(vista_url$results[[1]]$POR_VALIDOS,vista_url$results[[2]]$POR_VALIDOS),
            "total_votos" = c(vista_url$results[[1]]$TOTAL_VOTOS,vista_url$results[[2]]$TOTAL_VOTOS),
        )
})
```





```{r}
# x <- mutate(muestra, hora = paste(HORA,FECHA, sep = " - ")) %>% distinct(hora) 
# hora_general <- x$hora[1]
```

```{r}
totales <- 
    muestra %>% 
    mutate(
        dep = if_else(dep == "LIMA" & prov != "LIMA", "LIMA-PROVINCIAS", dep),
        dep = if_else(is.na(dep), "EXTRANJERO", dep),
        TOTAL_VOTOS = as.numeric(str_replace(TOTAL_VOTOS, ",", ""))
    ) %>% 
    filter(
        !AGRUPACION %in% no_contar
    ) %>% 
    group_by(dep, prov, dist) %>% 
    mutate(total_por_dist = sum(TOTAL_VOTOS)) %>% 
    ungroup() %>% 
    mutate(total_todo = sum(TOTAL_VOTOS)) %>% 
    group_by(AGRUPACION) %>%
    summarise(
        total = sum(TOTAL_VOTOS),
        validos = sum(total_por_dist * (as.numeric(POR_VALIDOS)/100)),
        # Se refiere al porcentaje de validos que tiene en este departamento
        por_validos = validos/total_todo * 100
    ) %>%
    ungroup() %>% 
    distinct() %>% 
    mutate(
        conteo = avance_general,
        hora = hora_general
    )
```

```{r}
totales %>% arrange(desc(total))
```


```{r}
res <- list()
for (index in 1:length(vista_general$results)){
    vec <- vista_general$results[[index]]
    if (any(sapply(vec, is.null))){
    
    }else{
        res[[index]] <- as_tibble(vec)
        
    }

}
totales <- bind_rows(res) %>% 
    mutate(
        validos = as.numeric(str_replace_all(TOTAL_VOTOS, ",", "")),
        total = validos,
        conteo = avance_general,
        hora = hora_general,
        por_validos = as.numeric(POR_VALIDOS)
    ) %>% 
    select(AGRUPACION, validos, total, conteo, hora, por_validos)
```



```{r}
totales %>% arrange(desc(total))
```

```{r}
bruto <- 
    muestra %>% 
    mutate(
        dep = if_else(dep == "LIMA" & prov != "LIMA", "LIMA-PROVINCIAS", dep),
        dep = if_else(is.na(dep), "EXTRANJERO", dep),
        TOTAL_VOTOS = as.numeric(str_replace(TOTAL_VOTOS, ",", ""))
    ) %>% 
    filter(
        !AGRUPACION %in% no_contar
    ) %>% 
    group_by(dep, prov, dist) %>% 
    mutate(total_por_dist = sum(TOTAL_VOTOS)) %>% 
    ungroup() %>% 
    group_by(dep) %>% 
    mutate(total_por_dep = sum(TOTAL_VOTOS)) %>% 
    group_by(AGRUPACION, dep) %>%
    summarise(
        total = sum(TOTAL_VOTOS),
        validos = sum(total_por_dist * (as.numeric(POR_VALIDOS)/100)),
        
        
        # Se refiere al porcentaje de validos que tiene en este departamento
        por_validos = validos/total_por_dep * 100,
        hora = paste(HORA,FECHA, sep = " - ")[1]
    ) %>%
    ungroup() %>% 
    distinct() %>% 
    bind_rows(
        totales %>% 
            mutate(dep = "TOTAL")
    )
```


```{r}
por_dep <- 
    bruto%>% 
    inner_join(mapper, by = c("AGRUPACION")) %>% 
    select(-contains("Unnamed"), -validos) %>% 
    rename(departamento = dep, validos=por_validos) %>% 
    mutate(region = tolower(departamento)) %>% 
    select(-AGRUPACION, -NOMBREe_CANDIDATO) %>% 
    left_join(
        avance_procesamiento_dep %>% select(dep, conteo=porcentaje_procesada), by = c("departamento"="dep")
    ) %>% 
    mutate(
        conteo = if_else(is.na(conteo.x), conteo.y, conteo.x),
        hora = hora_general
    ) %>% 
    select(-conteo.x, -conteo.y)
```

```{r}
nuevas <- 
    bind_rows(ubigeos_dep) %>% 
    mutate(
        hora = paste(hora, fecha, sep=" - "),
        conteo = as.numeric(por_actas_procesadas),
        departamento = dep,
        candidato = if_else(candidato=="JOSE PEDRO CASTILLO TERRONES", "Pedro Castillo", "Keiko Fujimori"),
        total = as.numeric(str_replace_all(total_votos, ",", "")),
        validos = as.numeric(por_validos)
    ) %>% 
    select(hora, conteo, departamento, candidato,total, validos)
```


```{r}
por_dep %>%
    select(-total, -validos, -hora, -conteo) %>%
    inner_join(nuevas, by = c("departamento", "candidato")) %>%
    bind_rows(por_dep %>% filter(departamento %in% c("LIMA-PROVINCIAS"))) %>%
    mutate(
        region = str_replace_all(region, " ", "-"),
        contabilizadas = vista_general$generals$generalData$POR_ACTAS_CONTABILIZADAS %>% as.numeric()
    ) %>%
    jsonlite::toJSON(., pretty = T) %>% write("../public/data/resultados_total.json")
```

Comprobando cual era el problema
```{r}
# nueva_ver <- 
#     por_dep %>%
#     select(-total, -validos, -hora, -conteo) %>%
#     inner_join(nuevas, by = c("departamento", "candidato")) %>%
#     bind_rows(por_dep %>% filter(departamento %in% c("LIMA-PROVINCIAS", "EXTRANJERO"))) %>%
#     mutate(region = str_replace_all(region, " ", "-"))
#     por_dep %>%
#     select(-total, -validos, -hora, -conteo) %>%
#     anti_join(nuevas, by = c("departamento", "candidato")) 

```
```{r}
# full_join(nueva_ver, por_dep, by = c("region","candidato", "partido", "departamento")) %>% View()
```


## Distritos
```{r}
brutodist <- 
    muestra %>% 
    group_by(ubigeo) %>% 
    mutate(
        total_votos_dist = sum( as.numeric(str_replace(TOTAL_VOTOS, ",", "")))
    ) %>% 
    ungroup() %>% 
    mutate(
        dep = if_else(dep == "LIMA" & prov != "LIMA", "LIMA-PROVINCIAS", dep),
    ) %>% 
    group_by(AGRUPACION, dep, prov, dist, ubigeo) %>% 
    summarise(
        total_votos = sum( as.numeric(str_replace(TOTAL_VOTOS, ",", ""))),
        validos = as.numeric(POR_VALIDOS),
        
        por_procesar = as.numeric(POR_PROCESAR),
        procesadas = as.numeric(ACTAS_PROCESADAS),
        total_actas = por_procesar + procesadas, 
        conteo = procesadas/total_actas * 100,
        conteo = 100 - as.numeric(POR_POR_PROCESAR),
        hora = paste(HORA,FECHA, sep = " - ")
    ) %>%
    ungroup() %>% ungroup() %>% 
    inner_join(mapper, by = c("AGRUPACION")) %>% 
    select(-contains("Unnamed")) %>% 
    mutate(
        departamento = str_to_title(dep),
        provincia = str_to_title(prov),
        distrito = str_to_title(dist),
        ubigeo_reniec = ubigeo
    ) %>% 
    inner_join(
        ubigeo_mapper %>% select(contains("ubigeo"))
    ) %>% 
    mutate(
        region = str_replace_all(tolower(departamento), " ", "-"),
        departamento_id = str_replace_all(tolower(departamento), " ", "-"),
        provincia_id = tolower(provincia),
        distrito_id = tolower(distrito)
    ) %>% 
    select(-AGRUPACION, -NOMBREe_CANDIDATO, -dep, -prov, -dist, -ubigeo, -por_procesar, -procesadas)

```


```{r, eval=F, echo=F}
for (i in distinct(brutodist, departamento_id)$departamento_id){
    cat('scp "../public/data/', str_replace_all(i, " ", "-"),'.json" antoniocucho@157.245.85.179:/var/www/ojo-publico.com/especiales/resultados-onpe-elecciones-2021/data/', end = "\n", sep = "")
}
```


```{r}
filter(brutodist, departamento_id=="amazonas") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/amazonas.json")
filter(brutodist, departamento_id=="ancash") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/ancash.json")
filter(brutodist, departamento_id=="apurimac") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/apurimac.json")
filter(brutodist, departamento_id=="arequipa") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/arequipa.json")
filter(brutodist, departamento_id=="ayacucho") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/ayacucho.json")
filter(brutodist, departamento_id=="cajamarca") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/cajamarca.json")
filter(brutodist, departamento_id=="callao") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/callao.json")
filter(brutodist, departamento_id=="cusco") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/cusco.json")
filter(brutodist, departamento_id=="huancavelica") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/huancavelica.json")
filter(brutodist, departamento_id=="huanuco") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/huanuco.json")
filter(brutodist, departamento_id=="ica") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/ica.json")
filter(brutodist, departamento_id=="junin") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/junin.json")
filter(brutodist, departamento_id=="la-libertad") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/la-libertad.json")
filter(brutodist, departamento_id=="lambayeque") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/lambayeque.json")
filter(brutodist, departamento_id=="lima") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/lima.json")
filter(brutodist, departamento_id=="lima-provincias") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/lima-provincias.json")
filter(brutodist, departamento_id=="loreto") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/loreto.json")
filter(brutodist, departamento_id=="madre-de-dios") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/madre-de-dios.json")
filter(brutodist, departamento_id=="moquegua") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/moquegua.json")
filter(brutodist, departamento_id=="pasco") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/pasco.json")
filter(brutodist, departamento_id=="piura") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/piura.json")
filter(brutodist, departamento_id=="puno") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/puno.json")
filter(brutodist, departamento_id=="san-martin") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/san-martin.json")
filter(brutodist, departamento_id=="tacna") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/tacna.json")
filter(brutodist, departamento_id=="tumbes") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/tumbes.json")
filter(brutodist, departamento_id=="ucayali") %>% jsonlite::toJSON(pretty = T) %>% write("../public/data/ucayali.json")
```




