---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readr)
library(stringr)
library(dplyr)
library(tidyr)
```


```{r}
data <- read_csv("congreso_sucio.csv")
candidatos_mapper <- read_csv("candidatos_lista_to_name.csv")
no_contar <- c("TOTAL DE VOTOS EMITIDOS", "VOTOS EN BLANCO", "VOTOS NULOS", "TOTAL DE VOTOS VÃLIDOS", "VOTOS BLANCOS")
candidatos_names <- read_csv("candidates_names.csv") %>% rename(AGRUPACION=partido, n_lista_candidato = NUMLISTA, region=departamento) %>% select(-TOTAL_VOTOS, -C_CODI_CANDIDATO)
curules_por_region <- read_csv("curules por region.csv")
```
```{r}
clean <- 
    data %>% 
    select(AGRUPACION, contains("TOTAL_VOTOS"), NLISTA, POR_VALIDOS, ELECTORES_HABIL, POR_ACTAS_PROCESADAS, N_CANDIDATOS, FECHA, HORA, POR_AVANCE, region) %>% 
    gather("lista", "voto_preferencial",  -AGRUPACION, - TOTAL_VOTOS, -NLISTA, -POR_VALIDOS, -ELECTORES_HABIL, -POR_ACTAS_PROCESADAS, -N_CANDIDATOS, -FECHA, -HORA, -POR_AVANCE, -region) %>% 
    mutate(
        n_lista_candidato = as.integer(str_replace(lista, "TOTAL_VOTOS", ""))
    ) %>% 
    filter(
        n_lista_candidato <= N_CANDIDATOS,
        !AGRUPACION %in% no_contar
    ) %>% 
    select(-NLISTA, -lista) %>% 
    mutate(
        region = if_else(region=="RESIDENTES EN EL EXTRANJERO", "RESIDENTES EXT", region)
    )

final <- 
    clean %>%
    left_join(candidatos_names) %>% 
    mutate(
        nombre = CANDIDATO,
        partido2 = AGRUPACION,
        partido = AGRUPACION,
        partido = case_when(
            partido == "FRENTE POPULAR AGRICOLA FIA DEL PERU - FREPAP" ~ "FREPAP",
            partido == "EL FRENTE AMPLIO POR JUSTICIA, VIDA Y LIBERTAD" ~ "FRENTE AMPLIO",
            partido == "PARTIDO DEMOCRATICO SOMOS PERU" ~ "SOMOS PERU",
            partido == "PARTIDO POLITICO NACIONAL PERU LIBRE" ~ "PERU LIBRE",
            partido == "AVANZA PAIS - PARTIDO DE INTEGRACION SOCIAL" ~"AVANZA PAIS",
            T ~ partido
        ),
        partido_id = str_replace_all(tolower(partido), " ", "-"),
        candidato_id = str_replace_all(tolower(CANDIDATO), " ", "-"),
        nro = n_lista_candidato
    ) %>% 
    select(-CANDIDATO, -n_lista_candidato, -AGRUPACION) %>% 
    left_join(distinct(candidatos_mapper, partido,color)) %>% 
    mutate(
        color = case_when(
            partido2 == "FRENTE POPULAR AGRICOLA FIA DEL PERU - FREPAP" ~ "#e3e3e3",
            partido2 == "EL FRENTE AMPLIO POR JUSTICIA, VIDA Y LIBERTAD" ~ "#4e5405",
            partido2 == "PARTIDO DEMOCRATICO SOMOS PERU" ~ "#ff2600",
            partido2 == "PARTIDO POLITICO NACIONAL PERU LIBRE" ~ "#f40201",
            partido2 == "AVANZA PAIS - PARTIDO DE INTEGRACION SOCIAL" ~"#ff2c79",
            partido2 == "PARTIDO POLITICO CONTIGO" ~"#333",
            T ~ color
        ),
    )

final %>% 
    write_csv("congreso_finalxd.csv")
```

```{r, eval=F, echo = F}
clean %>% anti_join(candidatos_names)
```


```{r}
anti_join(clean, candidatos_mapper, by = c("region"="departamento")) %>% distinct(region)
anti_join(candidatos_mapper, clean, by = c("departamento"="region")) %>% distinct(departamento)
```

```{r}
clean %>% 
    anti_join(
        candidatos_mapper %>% mutate(nro = as.integer(nro)),
        by = c("region"="departamento", "n_lista_candidato"="nro", "AGRUPACION"="partido")
    ) %>% 
    distinct(region, n_lista_candidato, AGRUPACION) %>% 
    distinct(AGRUPACION)
```

```{r}
candidatos_mapper %>%
    mutate(nro = as.integer(nro)) %>% 
    anti_join(
        clean,
        by = c("departamento"="region", "nro"="n_lista_candidato", "partido"="AGRUPACION")) %>% 
    distinct(partido)

```

```{r}
prop_nacionales <- 
    distinct(final, TOTAL_VOTOS, partido, region) %>% 
    mutate(total_nacional = sum(TOTAL_VOTOS)) %>% 
    group_by(partido) %>% 
    summarise(
        total_partido = sum(TOTAL_VOTOS),
        prop_validos_partido = total_partido/total_nacional
    ) %>% 
    distinct() %>% 
    arrange(desc(prop_validos_partido))
sum(prop_nacionales$prop_validos_partido)
```
```{r}
filter(prop_nacionales, prop_validos_partido > 0.05)

```
```{r}
por_partido <- 
    final %>% 
    distinct(TOTAL_VOTOS, partido, region, N_CANDIDATOS)
```


```{r}
# to_loop <- distinct(por_partido, region, N_CANDIDATOS)
to_loop <- curules_por_region
filtered_cont <- list()
for (index in 1:nrow(to_loop)){
    n <- to_loop$N_CANDIDATOS[index]
    reg <- to_loop$region[index]
    
    tmp <- filter(por_partido, region == get("reg"))
    cont <- tmp
    for (coef in 2:n){
        cont <- bind_rows(
            cont, 
            mutate(tmp, TOTAL_VOTOS = TOTAL_VOTOS/get("coef"), coef=get("coef"))
        )
    }
    filtered_cont[[index]] <- head(arrange(cont, desc(TOTAL_VOTOS)), n)
}
```

```{r}
first_round <- 
    bind_rows(filtered_cont) %>% 
    group_by(partido) %>%
    summarise(
        escanhos = n(),
        n_regiones = n_distinct(region)
    ) %>% 
    inner_join(prop_nacionales) %>% 
    arrange(desc(prop_validos_partido), desc(escanhos)) 
first_round
```

```{r}
to_keep <- first_round %>% filter(prop_validos_partido >= 0.05  | (n_regiones > 1 & escanhos >= 7))
```


```{r}
to_loop <- curules_por_region
new_filtered_cont <- list()
for (index in 1:nrow(to_loop)){
    n <- to_loop$N_CANDIDATOS[index]
    reg <- to_loop$region[index]
    
    tmp <- filter(por_partido, region == get("reg"), partido %in% to_keep$partido)
    cont <- tmp
    for (coef in 2:n){
        cont <- bind_rows(
            cont, 
            mutate(tmp, TOTAL_VOTOS = TOTAL_VOTOS/get("coef"), coef=get("coef"))
        )
    }
    new_filtered_cont[[index]] <- head(arrange(cont, desc(TOTAL_VOTOS)), n)
}
```

```{r}
final_filtered <- bind_rows(new_filtered_cont) 
```


```{r}
(congresistas_x_partido_x_region <- count(final_filtered,region,partido,sort=T) %>% rename(n_congresistas = n))
```
```{r}
congresistas <- 
    final %>% 
    mutate(
        nombre = if_else(partido=="FUERZA POPULAR" & region=="RESIDENTES EXT", "Juan Carlos Martin Lizarzaburu Lizarzaburu", nombre),
        nombre = if_else(partido=="RENOVACION POPULAR" & region=="RESIDENTES EXT", "JORGE ARTURO ZEBALLOS APONTE", nombre),
        candidato_id = str_replace_all(tolower(nombre), " ", "-"),
    ) %>% 
    filter(
        !is.na(nombre)
    ) %>% 
    inner_join(congresistas_x_partido_x_region) %>% 
    arrange(desc(voto_preferencial)) %>% 
    group_by(partido, region) %>% 
    mutate(
        orden = row_number()
    ) %>% 
    filter(orden <= n_congresistas)
```
```{r}
count(congresistas %>% ungroup(), partido, sort=T)
```
```{r}
congresistas_x_partido_x_region %>% group_by(partido) %>% summarise(x = sum(n_congresistas)) %>% arrange(desc(x))
```

```{r}
congreso_total <- 
    congresistas %>% 
    mutate(
        hora = paste(HORA,FECHA, sep = " - "),
        conteo = POR_ACTAS_PROCESADAS,
        nombre = str_to_title(nombre)
    ) %>% 
    select(region, nombre, candidato_id, partido, partido_id, nro, color, total_votos_partido = TOTAL_VOTOS, hora, conteo, voto_preferencial) #%>% 

congreso_total %>% 
    jsonlite::toJSON(., pretty = T) %>% write("../public/data/congreso_total.json")
```
